# Subcategory : Category
categories = {
    "Activities": "Entertainment",
    "Air travel": "Entertainment",
    "Gas": "Entertainment",
    "Lodging": "Entertainment",
    "Movies & DVDs": "Entertainment",
    "Public transportation": "Entertainment",
    "Rental car & taxi": "Entertainment",
    "Ride share": "Entertainment",
    "Scuba diving": "Entertainment",
    "Skiing": "Entertainment",
    "Beauty": "Merchandise",
    "Clothing": "Merchandise",
    "Electronics": "Merchandise",
    "Furnishings": "Merchandise",
    "Hobbies": "Merchandise",
    "Home supplies": "Merchandise",
    "Pets": "Merchandise",
    "Misc": "Merchandise",
    "Shopping": "Merchandise",
    "Rent": "Services",
    "Utilities": "Services",
    "Mobile phone": "Services",
    "Subscriptions": "Services",
    "Healthcare": "Services",
    "Beauty": "Services",
    "Other services": "Services",
    "Pet services": "Services",
    "Restaurant": "Dining",
    "Coffee shop": "Dining",
    "Fast food": "Dining",
    "Dessert": "Dining",
    "Groceries": "Groceries",
    "Income": "Work Income",
    "Income": "Interest Income",
    "Payment": "Payment",
}

# Rename Description if they contain the left side
desc = {
    "AIRBNB": "AirBnB",
    "APPLE.COM": "Apple",
    "CVS/PHARMACY #10127": "CVS #10127",
    "GglPay MORTON WILLIANEW YORK NY": "Morton Williams",
    "MNR ETIX TICKET": "MTA*MNR",
    "NYCT PAYGO": "OMNY",
    "SAMS SCAN-N-GO": "Sams Club",
    "SHEIN": "SHEIN.COM",
    "UBER   EATS": "Uber Eats",
    "UBER   ONE": "Uber One",
    "UBER   TRIP": "Uber Rides",
    "UBER EATS": "Uber Eats",
    "UBER ONE": "Uber One",
    "UBER RIDES": "Uber Rides",
    "WEEE": "Weee",
    "WHOLEFDS CIR": "Whole Foods Columbus Circle",
    "Wholefds": "Whole Foods",
    "amazon": "Amazon",
    "dunkin": "Dunkin Donuts",
    "morton williams": "Morton Williams",
    "starbucks": "Starbucks",
    "target": "Target",
}

# Rename Cateogry if the description contains the left side
recategorize_by_desc = {
    "NEW YORK ROAD RUNNERS": "Activities",
    "VITAL CLIMBING GYM": "Activities",
    "NYRR": "Activities",
    "Air Canada": "Air travel",
    "AMERICAN AIR": "Air travel",
    "Delta": "Air travel",
    "JETBLUE": "Air travel",
    "LOT AIRLINE": "Air travel",
    "Turkish air": "Air travel",
    "CITGO": "Gas",
    "Cider": "Clothing",
    "DSW.": "Clothing",
    "THREDUP": "Clothing",
    "Uniqlo": "Clothing",
    "BLACK FOX": "Coffee shop",
    "BLUE BOTTLE": "Coffee shop",
    "DAILYPROVISIONS": "Coffee shop",
    "Daily Provisions": "Coffee shop",
    "Starbucks": "Coffee shop",
    "CHICHA SAN CHEN": "Dessert",
    "EIGHT TURN CREP": "Dessert",
    "GONG CHA": "Dessert",
    "HEYTEA": "Dessert",
    "ICE CREAM": "Dessert",
    "insomnia cookies": "Dessert",
    "MOLLY TEA": "Dessert",
    "XING FU TANG": "Dessert",
    "YIFANG": "Dessert",
    "AMOREPIZZACAFE": "Fast food",
    "Chipotle": "Fast food",
    "CHICK FIL A": "Fast food",
    "Dunkin Donuts": "Fast food",
    "FIVE GUYS": "Fast food",
    "KFC": "Fast food",
    "TACO BELL": "Fast food",
    "TIM HORTONS": "Fast food",
    "MAIDEN LANE": "Healthcare",
    "MOUNT SINAI HOSPITAL": "Healthcare",
    "AirBnB": "Lodging",
    "AMC": "Movies & DVDs",
    "REGAL": "Movies & DVDs",
    "ANNUAL MEMBERSHIP FEE": "Other services",
    "CHEWY.COM": "Pets",
    "ETIX TICKET": "Public Transportation",
    "BILT REWARDS": "Rent",
    "Lyft": "Ride share",
    "Uber": "Ride share",
    "Uber One": "Ride share",
    "Uber Rides": "Ride share",
    "ASIAN JEWEL": "Restaurant",
    "HUNTER  F&B": "Restaurant",
    "JUST SALAD": "Restaurant",
    "NAN XIANG EXPRESS": "Restaurant",
    "OKEMO F&B": "Restaurant",
    "SQ *": "Restaurant",
    "SUSHICASTLE": "Restaurant",
    "Uber Eats": "Restaurant",
    "XIAN FAMOUS FOODS": "Restaurant",
    "COMFORT EXPRESS": "Skiing",
    "OVRRIDE": "Skiing",
    "Apple": "Subscriptions",
    "Spotify": "Subscriptions",
    "MTA": "Public transportation",
    "OMNY": "Public transportation",
    "PABT": "Public transportation",
    "PATH TAPP PAYGO CP": "Public transportation",
    "Spectrum": "Utilities",
    "CVS": "Groceries",
    "LIDL": "Groceries",
    "Morton Williams": "Groceries",
    "SAMS CLUB": "Groceries",
    "Sams Club": "Groceries",
    "SAMSCLUB": "Groceries",
    "Shaws": "Groceries",
    "target": "Groceries",
    "trader joe": "Groceries",
    "Weee": "Groceries",
    "Whole Foods": "Groceries",
    "Payment - Bilt Housing": "Payment",
    "CREDIT-CASH BACK REWARD": "Payment",
    "AUTOPAY": "Payment",
}
